"""initial

Revision ID: 6603fbdf6cd5
Revises: 
Create Date: 2026-05-05 12:09:37.017829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6603fbdf6cd5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='The primary key of the user'),
    sa.Column('username', sa.String(length=255), nullable=False, comment='Username'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's full name"),
    sa.Column('password', sa.String(length=255), nullable=False, comment="User's password"),
    sa.Column('phone', sa.String(length=255), nullable=True, comment="User's phone number"),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
