"""recreate users table

Revision ID: ca3255b30a2a
Revises: ca10aa0463a1
Create Date: 2026-05-05 17:08:21.037652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3255b30a2a'
down_revision: Union[str, Sequence[str], None] = 'ca10aa0463a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'SELLER', 'SUPER_ADMIN', name='userroles'), server_default='seller', nullable=False, comment="User's role"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
